global:
  log_level: "debug"

frontends:
  - name: "snmp"
    net: "tcp"
    address: "10.0.0.81:2030"
    tls_skip_verify: false
    tls_ca_cert_path: "/home/igor/ca/ca-cert.crt"
    tls_cert_path: "/home/igor/ca/server.crt"
    tls_pk_path: "/home/igor/ca/server.pk"
    backend_group: "snmp-transports"

backends:
  - name: "snmp-transports"
    servers:
      - name: "snmp1"
        net: "tcp"
        address: "10.0.0.81:2031"
        health_check_period_sec: 2
      - name: "snmp2"
        net: "tcp"
        address: "10.0.0.81:2032"
        health_check_period_sec: 5