[global]
  log_level="debug"

[[frontends]]
  name="snmp"
  net="tcp"
  address="10.0.0.81:2030"
  tls_skip_verify=false
  tls_ca_cert_path="/home/igor/ca/ca-cert.crt"
  tls_cert_path="/home/igor/ca/server.crt"
  tls_pk_path="/home/igor/ca/server.pk"
  backend_group="snmp-transports"
  ocsp_staple_enabled=true
  ocsp_responder_url="http://10.0.0.81:7777/"
  ocsp_cache_enabled=true
  ocsp_auto_renewal_enabled=false
  ocsp_validation_enabled=true

[[backends]]
  name="snmp-transports"
  [[backends.servers]]
    name="snmp1"
    net="tcp"
    address="10.0.0.81:3030"
    health_check_period_sec=2
  [[backends.servers]]
    name="snmp2"
    net="tcp"
    address="10.0.0.81:2032"
    health_check_period_sec=2
